Bitcoin-ABC/bitcoinabc.org

_posts/2018-08-20-announcing-bitcoin-abc-0-18-0-es.md

Depends on https://github.com/Bitcoin-ABC/bitcoinabc.org/pull/9 Since Github doesn't support stacked PRs, the only change here is adding the new translated post.

Spanish translation for 0.18.0 announcement

---

_includes/nav.html
_posts/2018-05-07-incident-report-es.md
_posts/2018-07-05-nov-hardfork-timeline-es.md
_posts/2018-08-15-benefits-of-ctor-es.md

Includes an inconsequential 1-liner of cleanup

Add new Spanish translations

---

_posts/2018-09-07-bitcoin-abc-and-the-block-size-limit.md

Note: contains a link to: https://www.bitcoinabc.org/2018-08-27-sharding-bitcoin-cash/
which will not be active until this PR is merged: https://github.com/Bitcoin-ABC/bitcoinabc.org/pull/17
I added a subtitle, open to suggestions for better subtitle if anyone has a better one.

Add Block Size Limit article

---

_posts/2018-09-26-incident-report.md

Open bracket was not closed. Fix by removing open bracket.

Fix bracket

---

_posts/2018-08-24-bitcoin-abc-vision-es.md

Co-authored-by: Leandro Di Marco <leandrodimarco@gmail.com>

Added Spanish translation for ABC vision + roadmap

---

_posts/2017-11-01-DAA-es.md
_posts/2017-12-01-dev-plan-es.md
_posts/2018-01-14-CashAddr-es.md
_posts/2018-04-01-upgrade-es.md
_posts/2018-05-07-incident-report-es.md
_posts/2018-08-08-nov-code-complete-reminder-es.md

Co-authored-by: Leandro Di Marco <leandrodimarco@gmail.com>

Added a bunch more Spanish translations of past articles.

---

_posts/2018-09-07-bitcoin-abc-and-the-block-size-limit-es.md

Co-authored-by: Leandro Di Marco <leandrodimarco@gmail.com>

Added Spanish translation for blocksize article

---

_posts/2018-09-26-incident-report-es.md

Co-authored-by: Leandro Di Marco <leandrodimarco@gmail.com>

Added Spanish translation for the latest incident report

---

index.html

I used the template from https://publish.twitter.com/#
This will help to easily convey quick information (eg. releases) on the website.
It looks good when I test locally, I'm not sure how to test for mobile.

Add Twitter feed embed

---

devfund.html

Accessible via bitcoinabc.org/devfund

Added stand-alone page for the BCH Dev Fund

---

_posts/2018-09-26-incident-report.md

The title is correct in the Spanish translation, so no fix needed there.

Fixed title in Sept 2018 incident report

---

index.html

Remove pre-upgrade notices

---

css/thermometer2.css

Tested locally, it seems to work.

Fix QR code in donation widget

---

devfund.html
index.html
js/thermometer2.js

Backport thermometer updates to bring donation goal to 1600 BCH

---

index.html

Bumped version number to 0.19.10

---

_posts/2019-08-08-kraken-cashaddr.md

Tested it locally, to make sure it renders fine.

Add post on Kraken switching to CashAddr

---

_posts/2019-08-08-kraken-cashaddr.md

"it's" should be "its"
Add accent to Amaury's name

Fix typo in Kraken post

---

_config-dev.yml
_config-prod.yml
_config.yml
_posts/2019-08-21-bitcoin-abc-0.20.0-ko.md

This is our first Korean translation, so added `ko` to the config as well.

Added Korean translation for upgrade article

---

_config-dev.yml
_config-prod.yml
_config.yml

The removed configs and comments are not used or needed.
Also exclude docker-compose.yml because it shouldn't be served from the site.

Cleanup Jekyll configs

---

nginx.conf

See https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/X-Frame-Options for more info.

Avoid clickjacking attacks by setting X-Frame-Options

---

_posts/2020-04-01-bitcoin-abc-launches-2020-fundraiser.md

Press release for 2020 funding campaign

---

_posts/2020-04-01-bitcoin-abc-launches-2020-fundraiser.md

After some local testing, I found that the colon in the title causes a problem.

Fix 2020 fundraiser post.
